### ISSUE TITLE
Dark theme - Scroll bar

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#130]
The scroll bar stays unaffected if the `dark theme` is used:
![image](https://user-images.githubusercontent.com/87228994/218260099-53e1eeec-3fa8-4aad-b19a-d9ecd0bc01e7.png)

I need to apply this CSS globally to make it work:

```css
@media (prefers-color-scheme: dark) {
  html {
    color-scheme: dark;
  }
}
```

Would be great, if this would work out of the box
